# Libraries

In [1]:
import pandas as pd
import numpy as np
import obiwan as obi
import datetime

# Read data

In [2]:
df_final = pd.read_excel('dataframes.xlsx', sheet_name='df_final')
df_final_semh = pd.read_excel('dataframes.xlsx', sheet_name='df_final_semh')
quarterly_ecb_data = pd.read_excel('dataframes.xlsx', sheet_name='quarterly_ecb_data') 
annual_ecb_data = pd.read_excel('dataframes.xlsx', sheet_name='annual_ecb_data')
monthly_ecb_data = pd.read_excel('dataframes.xlsx', sheet_name='monthly_ecb_data')

In [3]:
display(
df_final.head(),
df_final_semh.head(),
quarterly_ecb_data.head(),
annual_ecb_data.head(),
monthly_ecb_data.head()
       )

,Date,Current ratio-C18 Printing,Current ratio-J58 Publishing,Current ratio-H51 Air transport,Current ratio-G45 Trade motor vehicles,Current ratio-F Construction,Current ratio-C20 Chemicals,Current ratio-C17 Paper,Current ratio-I56 Food service activities,Current ratio-J63 Computer services,...,Financial pressure-Automobile-Manufact motor vehic-%,Financial pressure-Maritime-Sea transport-%,Financial pressure-Food manufact-%,Financial pressure-Info & communication-Telecommunic-%,Financial pressure-Footwear-%,Financial pressure-Transportation-%,Financial pressure-G Trade-%,Financial pressure-E Water and waste-%,Financial pressure-Transportation-Water transport-%,"Financial pressure-electricity, gas and water-%"
0,2006-12-31,109.00,130.65,171.56,114.21,154.95,130.67,179.64,71.24,138.54,...,8.49,8.46,14.03,6.61,19.74,26.74,20.17,15.80,6.67,15.97
1,2007-12-31,112.31,131.24,127.79,116.26,157.48,131.69,169.40,71.26,138.03,...,8.40,9.60,18.42,7.15,17.05,26.25,20.47,18.42,8.41,25.29
2,2008-12-31,111.10,124.05,125.44,110.88,155.37,121.80,109.99,68.58,153.76,...,12.78,12.92,23.11,8.71,19.27,39.93,26.48,21.95,15.00,29.61
3,2009-12-31,112.33,127.11,118.17,110.58,154.37,113.76,103.88,69.29,147.12,...,14.74,7.69,15.62,7.24,16.54,29.68,22.08,18.53,12.32,25.36
4,2010-12-31,127.30,122.00,151.35,115.62,143.78,123.69,116.35,74.92,144.28,...,10.63,10.31,17.34,2.35,18.41,22.03,22.01,18.60,23.16,23.89

,Unnamed: 0,Liquidez geral,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 215,Unnamed: 216,Unnamed: 217,Unnamed: 218,Unnamed: 219,Unnamed: 220,Unnamed: 221,Unnamed: 222,Unnamed: 223,Unnamed: 224
0,NaT,C18 Printing,J58 Publishing,H51 Air transport,G45 Trade motor vehicles,F Construction,C20 Chemicals,C17 Paper,I56 Food service activities,J63 Computer services,...,Automobile,Maritime,Food manufact,Info & communication,Footwear,Transportation,G Trade,E Water and waste,Transportation,"electricity, gas and water"
1,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2006-12-31,109,130.65,171.56,114.21,154.95,130.67,179.64,71.24,138.54,...,8.49,8.46,14.03,6.61,19.74,26.74,20.17,15.8,6.67,15.97
3,2007-12-31,112.31,131.24,127.79,116.26,157.48,131.69,169.4,71.26,138.03,...,8.4,9.6,18.42,7.15,17.05,26.25,20.47,18.42,8.41,25.29
4,2008-12-31,111.1,124.05,125.44,110.88,155.37,121.8,109.99,68.58,153.76,...,12.78,12.92,23.11,8.71,19.27,39.93,26.48,21.95,15,29.61

,TIME_PERIOD,"Private final consumption, Portugal","Gross fixed capital formation, Portugal","Gross entrepreneurial income of Non financial corporations as a ratio of gross value added, Portugal","Total financial assets of Non financial corporations (growth rate), Portugal","Total financial liabilities of Non financial corporations (growth rate), Portugal","Total financial assets of households (growth rate), Portugal","Loans granted to households (growth rate), Portugal","Total employment, Euro area 20 (fixed composition) as of 1 January 2023","Labour Productivity (per persons), Portugal"
0,2020-01-01,-1.008016,-1.259336,41.658218,0.784481,1.378025,1.363584,1.269223,0.483336,-1.965161
1,2020-04-01,-16.552394,-8.579667,40.736724,1.864120,2.037655,2.464528,1.091716,-2.743320,-14.673158
2,2020-07-01,-4.256041,-0.101212,40.767762,2.945065,2.310132,2.699639,1.518988,-1.968714,-3.452963
3,2020-10-01,-5.242758,0.570004,40.073375,3.916514,2.775165,2.953375,1.727187,-1.471045,-5.452797
4,2021-01-01,-7.222002,3.803724,40.641991,5.793014,3.842996,3.749417,2.179259,-1.291782,-2.692835

,TIME_PERIOD,"Government final consumption, Portugal","Imports of goods and services, Portugal","Exports of goods and services, Portugal","Gross domestic product at market prices, Portugal","Net value added of Non financial corporations (growth rate), Portugal","Gross entrepreneurial income of Non financial corporations, Portugal","Debt securities and loans of Non financial corporations as a ratio of GDP, Portugal","Debt of Non financial corporations as a ratio of total financial liabilities, Portugal","Total financial assets of Non financial corporations as a ratio of total financial assets, Portugal",...,"Gross saving of households as a ratio of adjusted gross disposable income, Portugal","Gross disposable income of households (growth rate), Portugal","Total financial assets of households as a ratio of total financial assets, Portugal","Loans granted to households as a ratio of total financial assets, Portugal","Gross fixed capital formation of households as a ratio of adjusted gross disposable income, Portugal","Final consumption expenditure of households (growth rate), Portugal","Government deficit(-) or surplus(+) (as % of GDP), Portugal","Government primary deficit(-) or surplus(+) (as % of GDP), Portugal","Government debt (consolidated) (as % of GDP), Portugal","Gross fixed capital formation, Portugal"
0,2020,0.398942,-11.590377,-18.334661,-8.204631,-11.474540,40.073375,92.290655,40.811918,3.916514,...,12.047856,-0.852711,2.953375,1.727187,5.449846,-6.355738,-5.752,-2.918,134.096,-2.341932
1,2021,3.784391,12.258844,12.034544,5.558758,8.613068,42.351140,87.851286,40.423061,3.778129,...,10.952782,5.629849,2.888199,3.740656,5.843595,7.037437,-2.825,-0.462,123.878,7.789368
2,2022,1.656845,11.265565,17.152864,6.985840,16.692040,42.801191,78.589222,38.947091,2.451700,...,7.329643,8.890484,1.733002,3.249446,5.917920,13.247677,-0.310,1.578,111.232,3.336517
3,2023,0.593048,1.796337,3.803727,2.613129,11.296385,41.402639,70.783122,36.839599,-1.509845,...,7.989961,7.221603,0.705166,0.126336,5.793576,6.432624,1.214,3.281,97.930,3.586178
4,2024,1.053851,4.769482,3.418246,1.899942,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.305466

  TIME_PERIOD  Unemployment rate, Portugal
0  2020-01-01                     6.781716
1  2020-02-01                     6.489416
2  2020-03-01                     5.843906
3  2020-04-01                     5.756566
4  2020-05-01                     6.093323

# Analysis